/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vue;




import java.sql.*;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;
import modele.Personne;

/**
 *
 * @author coline & mathilde
 */
public class PageInscription extends JFrame {
    Statement stmt;
    
    
    /**
     * Creates new form PageInscription
     */
    public PageInscription() throws SQLException, ClassNotFoundException {
        initComponents();
        affichage_table();
    }
    
     public ArrayList<Personne> getpersonnelist() throws SQLException, ClassNotFoundException{
        
        ArrayList<Personne> personnelist = new ArrayList<Personne>();
        
        Connection connection = DriverManager.getConnection("jdbc:mysql://localhost/gestion_ecole", "root", "");
        
        String query = "SELECT * FROM `personne`";
        
        ResultSet rset;
        
        try{
        //Class.forName("com.mysql.jdbc.Driver");
        Class.forName("com.mysql.cj.jdbc.Driver");
            stmt = connection.createStatement();
            rset = stmt.executeQuery(query);
            //System.out.println("rset : "+ rset); //return : com.mysql.cj.jdbc.result.ResultSetImpl@403e5912
            Personne p;
            while(rset.next()){
                p = new Personne(rset.getInt("id_personne"), rset.getString("nom_personne"), rset.getString("prenom_personne"), rset.getString("civilite"), rset.getString("type_personne"), rset.getString("Identifiant"), rset.getString("Mdp"));
                personnelist.add(p);
            }
        
        }catch (ClassNotFoundException | SQLException ex) {
                       ex.printStackTrace();
                    }
        
        return personnelist;
        
    }
    
    //Affichage table
    
    public void affichage_table() throws SQLException, ClassNotFoundException{
        
        ArrayList<Personne> list = getpersonnelist();
        DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
        Object[] row = new Object[7];
        for(int i = 0; i< list.size(); i++){
            
            row[0] = list.get(i).get_ID_Personne();
            System.out.println("row1: "+list.get(i).get_Nom_Personne());
            row[1] = list.get(i).get_Nom_Personne();
            row[2] = list.get(i).get_Prenom_Personne(); 
            row[3] = list.get(i).getCivilite();
            row[4] = list.get(i).get_Type_Personne();
            row[5] = list.get(i).getLogin();
            row[6] = list.get(i).getMdp();
            
            model.addRow(row);
            
        }
    }
    
  
 
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jTextFieldNom = new javax.swing.JTextField();
        jTextFieldPrenom = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jTextFieldIdentifiant = new javax.swing.JTextField();
        jTextFieldMdp = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        jTextFieldID = new javax.swing.JTextField();
        jTextFieldCivilite = new javax.swing.JTextField();
        jTextFieldTypePErsonne = new javax.swing.JTextField();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();
        jMenu3 = new javax.swing.JMenu();
        jMenu4 = new javax.swing.JMenu();
        jMenu5 = new javax.swing.JMenu();
        jMenu6 = new javax.swing.JMenu();
        jMenu7 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel1.setText("Formulaire d'inscription d'un élève");

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel2.setText("Nom :");

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel3.setText("Prénom : ");

        jTextFieldNom.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jTextFieldNom.setText("");
        jTextFieldNom.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldNomActionPerformed(evt);
            }
        });

        jTextFieldPrenom.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jTextFieldPrenom.setText("");
        
           jTextFieldPrenom.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldPrenomActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel4.setText("Civilité :");

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel5.setText("Type personne :");

        jButton1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jButton1.setText("S'inscrire");
        jButton1.addActionListener(new java.awt.event.ActionListener(){
    
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            try {
                jButton1ActionPerformed(evt);
            } catch (SQLException ex) {
                Logger.getLogger(PageInscription.class.getName()).log(Level.SEVERE, null, ex);
            }
                  }
        });
        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel6.setText("Identifiant :");

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel7.setText("Mot de passe :");

        jTextFieldIdentifiant.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jTextFieldIdentifiant.setText("");
        jTextFieldIdentifiant.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldIdentifiantActionPerformed(evt);
            }
        });

        jTextFieldMdp.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jTextFieldMdp.setText("");
       
      jTextFieldMdp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldMdpActionPerformed(evt);
            }
        });


        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Id", "Nom", "Prenom", "Civilité", "Type personne", "Identifiant", "Mdp"
            }
        ));
          jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
               JTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);
      
        jButton2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jButton2.setText("Modifier");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                
                try {
                    jButton2ActionPerformed(evt);
                } catch (SQLException ex) {
                    Logger.getLogger(PageInscription.class.getName()).log(Level.SEVERE, null, ex);
                }
              
            }
        });

        jButton3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        
        jButton3.setText("Supprimer");
         jButton3.addActionListener(new java.awt.event.ActionListener(){
             
         public void actionPerformed(java.awt.event.ActionEvent evt) {
                
                try {
                    jButton3ActionPerformed(evt);
                } catch (SQLException ex) {
                    Logger.getLogger(PageInscription.class.getName()).log(Level.SEVERE, null, ex);
                }
              
            }
        });
         
             
         

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel8.setText("Id :");

        jTextFieldID.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        

        jTextFieldCivilite.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jTextFieldCivilite.setText("");
           jTextFieldCivilite.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldCiviliteActionPerformed(evt);
            }
        });

        jTextFieldTypePErsonne.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jTextFieldTypePErsonne.setText("");
           jTextFieldTypePErsonne.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldTypePErsonneActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(333, 333, 333)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 382, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(62, 62, 62))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(44, 44, 44)
                                        .addComponent(jButton1))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addContainerGap()
                                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(45, 45, 45)
                                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(59, 59, 59)
                                .addComponent(jLabel3))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(80, 80, 80)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel8))))
                        .addGap(53, 53, 53)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jTextFieldPrenom, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTextFieldNom, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTextFieldIdentifiant, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTextFieldMdp, javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jButton2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 58, Short.MAX_VALUE)
                        .addComponent(jButton3))
                    .addComponent(jTextFieldID)
                    .addComponent(jTextFieldCivilite)
                    .addComponent(jTextFieldTypePErsonne))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 38, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 509, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(39, 39, 39))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 37, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(2, 2, 2)
                                .addComponent(jLabel8))
                            .addComponent(jTextFieldID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(jTextFieldNom, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(31, 31, 31)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextFieldPrenom, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3))
                        .addGap(37, 37, 37)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextFieldCivilite, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(28, 28, 28)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextFieldTypePErsonne, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(28, 28, 28)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextFieldIdentifiant, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextFieldMdp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButton1)
                            .addComponent(jButton2)
                            .addComponent(jButton3)))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 427, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(64, 64, 64))
        );

        jMenu1.setText("Ecole");
        jMenuBar1.add(jMenu1);

        jMenu2.setText("Classe");
        jMenuBar1.add(jMenu2);

        jMenu3.setText("Niveau");
        jMenuBar1.add(jMenu3);

        jMenu4.setText("Discipline");
        jMenuBar1.add(jMenu4);

        jMenu5.setText("Enseignement");
        jMenuBar1.add(jMenu5);

        jMenu6.setText("Bulletin");
        jMenuBar1.add(jMenu6);

        jMenu7.setText("Reporting");
        jMenuBar1.add(jMenu7);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>       
    

    
     
    
    public void jTextFieldIdentifiantActionPerformed(java.awt.event.ActionEvent evt) {                                            
        // TODO add your handling code here:
    }                                           

    public void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {                                           
        // TODO add your handling code here:
    }                                          

    public void jTextFieldNomActionPerformed(java.awt.event.ActionEvent evt) {                                            
        // TODO add your handling code here:
    }     
       public void jTextFieldPrenomActionPerformed(java.awt.event.ActionEvent evt) {                                            
        // TODO add your handling code here:
    }  
         public void jTextFieldMdpActionPerformed(java.awt.event.ActionEvent evt) {                                            
        // TODO add your handling code here:
    }     
    
               public void jTextFieldIDActionPerformed(java.awt.event.ActionEvent evt) {                                            
        // TODO add your handling code here:
    }     
    
                     public void jTextFieldCiviliteActionPerformed(java.awt.event.ActionEvent evt) {                                            
        // TODO add your handling code here:
    }     
          public void jTextFieldTypePErsonneActionPerformed(java.awt.event.ActionEvent evt) {                                            
        // TODO add your handling code here:
    }     
    
    
    
    
    
    public void executeSQLQuery(String query, String message) throws SQLException{
        
        Connection con = DriverManager.getConnection("jdbc:mysql://localhost/gestion_ecole", "root", "");
        Statement stmt;
        try{
            
            stmt = con.createStatement();
            if(stmt.executeUpdate  (query) == 1){
                
                DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
                model.setRowCount(0);
                affichage_table();
                JOptionPane.showMessageDialog(null, "Data " + message + " Reussie");
            }else{
                
                JOptionPane.showMessageDialog(null, "Data Not " + message);
            }
        }catch(Exception ex){
            
            ex.printStackTrace();
        }
    } 
    
    public void jButton1ActionPerformed(java.awt.event.ActionEvent evt) throws SQLException {                                         
        // TODO add your handling code here:
        
        String query = "INSERT INTO `personne` (`id_personne`, `nom_personne`, `prenom_personne`, `civilite`, `type_personne`, `Identifiant`, `Mdp`) VALUES ( '"+ jTextFieldID.getText()+"','" + jTextFieldNom.getText()+"','" + jTextFieldPrenom.getText()  +"','" + jTextFieldCivilite.getText()  +"','" +jTextFieldTypePErsonne.getText()  +"','" + jTextFieldIdentifiant.getText()  +"','" + jTextFieldMdp.getText() + "')";
        executeSQLQuery(query, "Inserted");
    } 
    
    public void jButton2ActionPerformed(java.awt.event.ActionEvent evt) throws SQLException {                                         
        // TODO add your handling code here:
        
        String query = "UPDATE personne SET nom_personne = '" + jTextFieldNom.getText().toString() +
                "', prenom_personne = '" + jTextFieldPrenom.getText().toString() + 
                "', civilite = '" + jTextFieldCivilite.getText().toString() + 
                "', type_personne = '" +   jTextFieldTypePErsonne.getText().toString() + 
                "', Identifiant = '" +   jTextFieldIdentifiant.getText().toString() + 
                "', Mdp = '" + jTextFieldMdp.getText().toString() + 
                "' WHERE id_personne = " +Integer.valueOf(jTextFieldID.getText().toString()).intValue()+"";
        stmt.executeUpdate(query);
    } 
    
    public void jButton3ActionPerformed(java.awt.event.ActionEvent evt) throws SQLException {                                         
        // TODO add your handling code here:
        
        String query = "DELETE FROM `personne` WHERE `id_personne` = " + jTextFieldID.getText();
        executeSQLQuery(query, "Supprimé");
    } 
    
    public void JTable1MouseClicked(java.awt.event.MouseEvent evt){
        
        int i = jTable1.getSelectedRow();
        TableModel model = jTable1.getModel();
        jTextFieldID.setText(model.getValueAt(i, 0).toString());
        jTextFieldNom.setText(model.getValueAt(i, 1).toString());
        jTextFieldPrenom.setText(model.getValueAt(i, 2).toString());
        jTextFieldCivilite.setText(model.getValueAt(i, 3).toString());
        jTextFieldTypePErsonne.setText(model.getValueAt(i, 4).toString());                
        jTextFieldIdentifiant.setText(model.getValueAt(i, 5).toString());
        jTextFieldMdp.setText(model.getValueAt(i, 6).toString());
        
        
    }

     /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PageEleve.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PageEleve.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PageEleve.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PageEleve.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                PageInscription pg = null;
                try {
                    try {
                        pg = new PageInscription();
                    } catch (ClassNotFoundException ex) {
                        Logger.getLogger(PageInscription.class.getName()).log(Level.SEVERE, null, ex);
                    }
                } catch (SQLException ex) {
                    Logger.getLogger(PageConnexion.class.getName()).log(Level.SEVERE, null, ex);
                }
        pg.setVisible(true);
        pg.setTitle("Inscription");
        pg.setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        pg.setSize(1000,600);
        
        pg.setResizable(false); //empêche le redimensionnement
        pg.setLocationRelativeTo(null); //fenêtre positionné au centre de l'écran de l'ordinateur
            
            }
        });
    }

     // Variables declaration - do not modify                     
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenu jMenu6;
    private javax.swing.JMenu jMenu7;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextFieldNom;
    private javax.swing.JTextField jTextFieldPrenom;
    private javax.swing.JTextField jTextFieldIdentifiant;
    private javax.swing.JTextField jTextFieldMdp;
    private javax.swing.JTextField jTextFieldID;
    private javax.swing.JTextField jTextFieldCivilite;
    private javax.swing.JTextField jTextFieldTypePErsonne;
    // End of variables declaration                   
}





