/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vue;

import controleur.DAOEcole;
import java.sql.*;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import modele.*;

/**
 * Classe qui permet de faire la connexion entre l'interface graphique et la BDD
 * @author LOIC
 */
public class PageConnexion extends JFrame{
     // Variables declaration - do not modify 
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    // End of variables declaration   
    
    /**
     *
     */
    public PageConnexion() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    public void initComponents() {
        System.out.println("Init components");
        
        this.setTitle("Connexion");
        this.setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
         this.setSize(1000,1000);
        this.setResizable(false); //empêche le redimensionnement
        this.setLocationRelativeTo(null); //fenêtre positionné au centre de l'écran de l'ordinateur
       
       

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();

        getContentPane().setLayout(null);

        jPanel1.setLayout(null);
        this.getContentPane().add(jPanel1);
        jPanel1.setBounds(122, 11, 0, 0);

        jPanel2.setLayout(null);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel1.setText("    Accueil");
        jPanel2.add(jLabel1);
        jLabel1.setBounds(160, 30, 110, 40);

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel2.setText("Identifiant : ");
        jPanel2.add(jLabel2);
        jLabel2.setBounds(70, 110, 120, 30);

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel3.setText("Mot de passe :");
        jPanel2.add(jLabel3);
        jLabel3.setBounds(60, 180, 140, 30);

        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });
        jPanel2.add(jTextField1);
        jTextField1.setBounds(230, 110, 150, 30);

        jTextField2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField2ActionPerformed(evt);
            }
        });
        jPanel2.add(jTextField2);
        jTextField2.setBounds(230, 190, 150, 30);

        jButton1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jButton1.setText("Se connecter");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                try {
                    System.out.println("Vous avez appuyé sur le boutton connexion ");
                    jButton1ActionPerformed(evt);
                } catch (SQLException ex) {
                    Logger.getLogger(PageConnexion.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
        jPanel2.add(jButton1);
        jButton1.setBounds(60, 270, 150, 30);

        jButton2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jButton2.setText("Quitter");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton2);
        jButton2.setBounds(260, 270, 120, 30);
        jPanel2.add(jLabel4);
        jLabel4.setBounds(190, 260, 140, 20);

        this.getContentPane().add(jPanel2);
        jPanel2.setBounds(0, 0, 470, 400);
        

        pack();
    }// </editor-fold>                        

    /**
     *
     * @param evt
     * @throws SQLException
     */
    public void jButton1ActionPerformed(java.awt.event.ActionEvent evt) throws SQLException{                                         
        // TODO add your handling code here:
        
        int i=0;
        String identifiant = jTextField1.getText().toString();
        String mdp = jTextField2.getText().toString();
        System.out.println("Vous avez rentré l'identifiant : "+identifiant);
        System.out.println("Vous avez rentré le mot de passe : "+mdp);
        BDD bdd = new BDD(); //instancie et récupère la base de données 
        
        for(Personne P : bdd.getListPersonne()){
            boolean b1 = P.getLogin().equals(identifiant);
            boolean b2 = P.getMdp().equals(mdp);
            //System.out.println("login : "+P.getLogin()+"\tmdp : "+P.getMdp()+"\tb1 = "+b1+"\tb2 = "+b2);
            if(b1 && b2){
                System.out.println("Connexion réussie !");
                i=1;
                //JOptionPane.showMessageDialog(null, "Connexion reussie!");
                if(P.get_Type_Personne().equals("Elève")){
                    JOptionPane.showMessageDialog(null, "C'est un élève !");
                    //METTRE PROGRAMME PAGE ELEVE
                    this.setVisible(false);
                    
                    PageEleve2 pgEleve = new PageEleve2(P);
                    pgEleve.setVisible(true); //cache la fenêtre de connexion
                    
                }
                else if (P.get_Type_Personne().equals("Admin")){
                    JOptionPane.showMessageDialog(null, "C'est un admin !");
                    //METTRE PROGRAMME PAGE PROFESSEUR
                    this.setVisible(false);
                    try {
                        PageInscription pgIns = new PageInscription();
                        pgIns.setVisible(true);
                    } catch (ClassNotFoundException ex) {
                        Logger.getLogger(PageConnexion.class.getName()).log(Level.SEVERE, null, ex);
                    }
                }
                else if (P.get_Type_Personne().equals("Enseignant")){
                    JOptionPane.showMessageDialog(null, "C'est un professeur !");
                    //METTRE PROGRAMME PAGE PROFESSEUR
                    this.setVisible(false);
                    PageEnseignant2 pgEnseignant = new PageEnseignant2(P);
                    pgEnseignant.setVisible(true);
                }
                
            }
        }
        
        if(i==0){
            //message d'erreur dans le cas où l'utilisateur n'a pas réussi à se connecter
            JOptionPane.showMessageDialog(null, "Connexion échouée! Les informations saisies ne sont pas correctes!");
        }
        
        
        
        /*
        //Même manière de procéder avec SQL
        try{
            //Class.forName("com.mysql.jdbc.Driver");
            Class.forName("com.mysql.cj.jdbc.Driver");
            Connection conn = DriverManager.getConnection("jdbc:mysql://localhost/gestion_ecole", "root", "");
            Statement stmt = conn.createStatement();
            ResultSet result = stmt.executeQuery("SELECT * FROM personne"); 
            int j=0;
            while(result.next()){
                String id = result.getString("Identifiant");
                String mdp1 = result.getString("Mdp");
                
                if(id.equals(identifiant) && mdp1.equals(mdp)){
                    JOptionPane.showMessageDialog(null, "Connexion reussie!");
                    j=1;
                }
            }
            if(j==0){
                JOptionPane.showMessageDialog(null, "Connexion échouée! Les informations saisies ne sont correctes!");
            }
        }catch(SQLException ex){
            ex.printStackTrace();
        }*/
    }                                      

    /**
     *
     * @param evt
     */
    public void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {                                         
        // TODO add your handling code here:
        
        System.exit(0);
    }                                        

    /**
     *
     * @param evt
     */
    public void jTextField2ActionPerformed(java.awt.event.ActionEvent evt) {                                            
        // TODO add your handling code here:
    }                                           

    /**
     *
     * @param evt
     */
    public void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {                                            
        // TODO add your handling code here:
    }                                           

    /**
     *
     * @param args
     */
    public static void main(String args[]) {
        
        PageConnexion pg = new PageConnexion();
        pg.setVisible(true);
        pg.setTitle("Connexion");
        pg.setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        pg.setSize(500,430);
        pg.setResizable(false); //empêche le redimensionnement
        pg.setLocationRelativeTo(null); //fenêtre positionné au centre de l'écran de l'ordinateur
       
         
    }

    
}
